In [28]:
from IPython.display import clear_output
import time
import pandas as pd
from Chandelier_ZLSMA_Filter_Future import *
from Chandelier_ZLSMA import *
from Support_Resistance_Future_Scaner import *
from Display_Future import *
from Buy_Sell_Presure_Scaner import *
    
def scanner():
    active_symbols = Support_Resistance.get_active_symbols()
    btc_out = only_chandelier("BTCUSDT")
    btc_out = btc_out[198:]
    out_buy = int(btc_out['buy_signal'].sum())
    BTC_Support_Resistance = pd.DataFrame(Support_Resistance.Support_Resistance_P(['BTCUSDT']))


    if out_buy == 2:
        if BTC_Support_Resistance['near_resistance'][0] != True:
            print("Long Signal...")
            results_long = Chandelier_ZLSMA_Scan(
                coin_list=active_symbols,
                signal_type='buy'
            )
            alts_long =  pd.DataFrame(Support_Resistance.Support_Resistance_P(results_long['symbol'].tolist()))
            alts_long = alts_long[alts_long['signal'] != 'RESISTANCE']
            results_long = Chandelier_ZLSMA_Scan(
                coin_list=alts_long['symbol'].tolist(),
                signal_type='buy'
            )
        
    else:
        if BTC_Support_Resistance['near_support'][0] != True:
            print("Short Signal...")
            results_short = Chandelier_ZLSMA_Scan(
                coin_list=active_symbols,
                signal_type='sell'
            )
            alts_short =  pd.DataFrame(Support_Resistance.Support_Resistance_P(results_short['symbol'].tolist()))
            alts_short = alts_short[(alts_short['signal'] == 'RESISTANCE') | (alts_short['signal'] == 'NEUTRAL')]
            results_short = Chandelier_ZLSMA_Scan(
                coin_list=alts_short['symbol'].tolist(),
                signal_type='sell'
            )
            
    return alts_long if 'alts_long' in locals() else alts_short if 'alts_short' in locals() else None

In [29]:
out = scanner()

--------------------------------------------------------------------------------
Scan complete. Found 5 coins matching criteria.
Scanning 1000CHEEMSUSDT...
Scanning EPTUSDT...
Scanning B2USDT...
Scanning SCRTUSDT...
Scanning ZETAUSDT...
--------------------------------------------------------------------------------
Scan complete. Found 4 coins matching criteria.

In [30]:
out

,symbol,current_price,signal,rsi,change_24h,volume_24h,quote_volume_24h,near_support,support_level,support_strength,near_resistance,resistance_level,resistance_strength,total_support_levels,total_resistance_levels,poc_price,near_poc,contract_type
0,1000CHEEMSUSDT,0.001404,NEUTRAL,66.38,4.51,4.297466e+09,6.021620e+06,False,None,0,False,None,0,4,2,0.001351,False,PERPETUAL
1,EPTUSDT,0.004626,NEUTRAL,59.01,3.10,1.562075e+09,6.985018e+06,False,None,0,False,None,0,2,3,0.004321,False,PERPETUAL
2,B2USDT,0.378000,NEUTRAL,32.93,-2.12,5.126230e+06,1.991097e+06,False,None,0,False,None,0,3,3,0.366180,False,PERPETUAL
3,SCRTUSDT,0.186800,NEUTRAL,62.96,5.06,8.387997e+06,1.539200e+06,False,None,0,False,None,0,2,2,0.164282,False,PERPETUAL
4,ZETAUSDT,0.229500,NEUTRAL,63.74,6.00,6.445297e+07,1.468901e+07,False,None,0,False,None,0,2,1,0.212668,False,PERPETUAL

In [16]:
from Future_Trade_Execution import *

2025-07-14 18:10:34,646 - INFO - ✅ Connected to Binance Futures successfully!
2025-07-14 18:10:34,647 - INFO - 💰 USDT Balance: $8.65
2025-07-14 18:10:34,648 - INFO - 🔄 FIXED monitoring loop started - checking every 0.3s
2025-07-14 18:10:34,648 - INFO - 👁️ FIXED monitoring started
2025-07-14 18:10:34,648 - INFO - 🚀 COMPLETELY FIXED SELF-MONITORING TRADER READY!
2025-07-14 18:10:34,649 - INFO - 🔧 ALL CRITICAL FIXES APPLIED:
2025-07-14 18:10:34,649 - INFO -    ✅ FIXED: Stop Loss automated execution
2025-07-14 18:10:34,649 - INFO -    ✅ FIXED: Take Profit automated execution
2025-07-14 18:10:34,649 - INFO -    ✅ FIXED: 1.5% liquidation safety buffer
2025-07-14 18:10:34,649 - INFO -    ✅ FIXED: Reliable price monitoring
2025-07-14 18:10:34,650 - INFO -    ✅ FIXED: Precise trigger logic
2025-07-14 18:10:34,650 - INFO -    ✅ FIXED: Order execution with retries
2025-07-14 18:10:34,650 - INFO -    ✅ FIXED: Position verification
2025-07-14 18:10:34,651 - INFO -    ✅ FIXED: Ultra-fast monitoring (0.3s)

2025-07-14 18:11:35,573 - ERROR - ❌ Error fetching position info: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v2/positionRisk?symbol=MOCAUSDT&timestamp=1752484290502&signature=27e0b4cba16ecb883d29159dc031ef4925d769364b7d7f1c6763dd6a105cdfcb
2025-07-14 18:11:35,576 - INFO - 📊 Position MOCAUSDT closed externally
2025-07-14 18:11:35,586 - INFO - 📊 Trade exit recorded: PnL $-0.17 (-2.17%)
2025-07-14 18:11:35,587 - INFO -    Duration: 0.8 minutes
2025-07-14 18:43:14,911 - ERROR - ❌ Error fetching position info: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v2/positionRisk?symbol=EPTUSDT&timestamp=1752486189841&signature=64f3e5d70f6e991a9be2d6af637e19ef95554ede31ab74cc80c0611736be1105
2025-07-14 18:43:14,913 - INFO - 📊 Position EPTUSDT closed externally
2025-07-14 18:43:14,924 - INFO - 📊 Trade exit recorded: PnL $-0.40 (-5.01%)
2025-07-14 18:43:14,925 - INFO -    Duration: 17.9 minutes

In [31]:
# Example 1: Basic long trade with 1:2 risk/reward
self_monitoring_trader.trade("EPTUSDT", 8, leverage=10, side="short", 
                            use_atr_stoploss=True, atr_multiplier=2.0, take_profit_ratio=2)



# # Example: Make exactly $50 profit
# self_monitoring_trader.trade("1000000BOBUSDT", 6, leverage=10, side="short", 
#                         fixed_tp_dollars=1, use_atr_stoploss=True, atr_multiplier=1.8)

2025-07-14 18:25:21,395 - INFO - 📊 Using symbol: EPTUSDT (base: EPT)
2025-07-14 18:25:21,395 - INFO - 🚀 INITIATING COMPLETELY FIXED TRADE: EPT SHORT
2025-07-14 18:25:21,396 - INFO - 💰 Margin: $8 | Leverage: 10x
2025-07-14 18:25:21,396 - INFO - 🛡️ Liquidation Safety: EXACTLY 1.5% buffer
2025-07-14 18:25:21,396 - INFO - 🔧 ALL CRITICAL FIXES APPLIED!
2025-07-14 18:25:21,544 - INFO - 📊 Current price: $0.00459200
2025-07-14 18:25:21,546 - INFO - 📊 Position size: -17421.60278745 EPT
2025-07-14 18:25:21,547 - INFO - 📊 Notional: $80.00
2025-07-14 18:25:21,602 - INFO - ⚡ Leverage set to 10x
2025-07-14 18:25:21,653 - INFO - 🔒 Isolated margin mode set
2025-07-14 18:25:21,655 - INFO - 🎯 Calculated Liquidation: $0.00510222
2025-07-14 18:25:21,657 - INFO -    MMR: 1.0%
2025-07-14 18:25:21,658 - INFO - 📈 Fetching chart data...
2025-07-14 18:25:21,752 - INFO - 📊 ATR: $0.00007327
2025-07-14 18:25:21,753 - INFO - 🛡️ CALCULATING SAFE STOP LOSS WITH 1.5% BUFFER...
2025-07-14 18:25:21,753 - INFO - 🛡️ SAFE STOP CALCULATED: $0.00473855
2025-07-14 18:25:21,753 - INFO -    Distance from liquidation: 7.92%
2025-07-14 18:25:21,754 - INFO -    Safety buffer: 1.5%
2025-07-14 18:25:21,754 - INFO - 🔥 EXECUTING COMPLETELY FIXED ORDER...
2025-07-14 18:25:21,849 - INFO - ✅ ORDER EXECUTED at $0.00459200
2025-07-14 18:25:21,849 - INFO - 🎯 Fetching ACTUAL liquidation price...
2025-07-14 18:25:22,922 - INFO - ✅ ACTUAL Liquidation: $0.00497429
2025-07-14 18:25:22,924 - INFO - 🛡️ SAFE STOP CALCULATED: $0.00473855
2025-07-14 18:25:22,927 - INFO -    Distance from liquidation: 5.13%
2025-07-14 18:25:22,929 - INFO -    Safety buffer: 1.5%
2025-07-14 18:25:22,950 - INFO - 📊 Trade data saved to: futures_trading_report_2025-07-14.csv
2025-07-14 18:25:22,952 - INFO - ✅ COMPLETELY FIXED TRADE COMPLETED!
2025-07-14 18:25:22,953 - INFO -    Symbol: EPTUSDT
2025-07-14 18:25:22,955 - INFO -    Side: SHORT
2025-07-14 18:25:22,956 - INFO -    Entry: $0.00459200
2025-07-14 18:25:22,958 - INFO -    🎯 ACTUAL Liquidation: $0.00497429
2025-07-14 18:25:22,959 - INFO -    🛡️ Safe Stop: $0.00473855
2025-07-14 18:25:22,961 - INFO -    🎯 Take Profit: $0.00429890
2025-07-14 18:25:22,962 - INFO -    Quantity: -17421.60278745 EPT
2025-07-14 18:25:22,963 - INFO -    Margin: $8
2025-07-14 18:25:22,965 - INFO -    🛡️ FINAL Safety Distance: 8.33%
2025-07-14 18:25:22,966 - INFO -    TP Type: ATR SL/TP (1:2 R:R)
2025-07-14 18:25:22,968 - INFO - 🚀 TRADE IS NOW UNDER COMPLETELY FIXED MONITORING!
2025-07-14 18:25:22,969 - INFO - ✅ ALL 4 CRITICAL ISSUES FIXED:
2025-07-14 18:25:22,971 - INFO -    🎯 Stop Loss: Automated with precise triggers
2025-07-14 18:25:22,972 - INFO -    🎯 Take Profit: Automated with precise triggers
2025-07-14 18:25:22,974 - INFO -    🛡️ Liquidation Safety: EXACTLY 1.5% buffer
2025-07-14 18:25:22,975 - INFO -    📊 Price Monitoring: Ultra-reliable multi-source
2025-07-14 18:25:22,976 - INFO -    ⚖️ Risk/Reward: 1:2.00
2025-07-14 18:25:22,976 - INFO -    👁️ Monitoring every 0.3 seconds
2025-07-14 18:25:22,976 - INFO -    🔧 Order execution with retries and verification
2025-07-14 18:25:22,976 - INFO -    📊 All trades recorded to CSV automatically

{'success': True,
 'symbol': 'EPTUSDT',
 'coin': 'EPT',
 'side': 'short',
 'leverage': 10,
 'entry_price': 0.004592,
 'actual_liquidation_price': 0.00497429,
 'quantity': -17421.60278745,
 'margin_used': 8,
 'stop_loss': np.float64(0.004738548325568957),
 'take_profit': np.float64(0.004298903348862085),
 'tp_type': 'ATR SL/TP (1:2 R:R)',
 'liquidation_safety_distance': 8.325130662020916,
 'liquidation_safety_buffer': 1.5,
 'risk_reward_ratio': np.float64(2.0000000000000058),
 'trade_id': 'EPTUSDT_1752485122',
 'monitoring_status': 'COMPLETELY_FIXED_ACTIVE',
 'all_critical_fixes_applied': True}

In [42]:
monitor.start_continuous_monitoring()

Monitoring is already running!

In [27]:
self_monitoring_trader.close_position("MOCAUSDT", reason="MANUAL_EXIT")

2025-07-14 18:19:37,092 - INFO - 📊 Using symbol: MOCAUSDT (base: MOCA)
2025-07-14 18:19:37,093 - INFO - 🔄 CLOSING POSITION: MOCA
2025-07-14 18:19:37,234 - INFO - 📊 Current price: $0.08282000
2025-07-14 18:19:37,236 - INFO - 📊 Position: LONG 964.00000000 MOCA
2025-07-14 18:19:37,237 - INFO - 🔥 EXECUTING CLOSING ORDER...
2025-07-14 18:19:37,317 - INFO - ✅ POSITION CLOSED - MOCA
2025-07-14 18:19:37,318 - INFO - 💰 Exit Price: $0.08285230
2025-07-14 18:19:37,342 - INFO - 📊 Trade exit recorded: PnL $-0.08 (-0.96%)
2025-07-14 18:19:37,344 - INFO -    Duration: 4.0 minutes
2025-07-14 18:19:37,345 - INFO - 🚫 Removed MOCAUSDT from monitoring

True

Loop_In_Bot

In [10]:
from SMC import *
from SMC_FGV import *
from Up_Down_Trend_Scanner import *

from IPython.display import clear_output
import time
import pandas as pd
from Chandelier_ZLSMA_Filter_Future import *
from Chandelier_ZLSMA import *
from Support_Resistance_Future_Scaner import *
from Display_Future import *
from Buy_Sell_Presure_Scaner import *

In [11]:
scanner = Binance_Support_Resistance_Perpetual_Scanner()
active_symbols = scanner.get_active_symbols()

In [12]:
downtrends = downtrend_scanner(active_symbols, timeframe='15m')

Scanning 447 symbols...
Progress: 10/447
Progress: 20/447
Progress: 30/447
Progress: 40/447
Progress: 50/447
Progress: 60/447
Progress: 70/447
Progress: 80/447
Progress: 90/447
Progress: 100/447
Progress: 110/447
Progress: 120/447
Progress: 130/447
Progress: 140/447
Progress: 150/447
Progress: 160/447
Progress: 170/447
Progress: 180/447
Progress: 190/447
Progress: 200/447
Progress: 210/447
Progress: 220/447
Progress: 230/447
Progress: 240/447
Progress: 250/447
Progress: 260/447
Progress: 270/447
Progress: 280/447
Progress: 290/447
Progress: 300/447
Progress: 310/447
Progress: 320/447
Progress: 330/447
Progress: 340/447
Progress: 350/447
Progress: 360/447
Progress: 370/447
Progress: 380/447
Progress: 390/447
Progress: 400/447
Progress: 410/447
Progress: 420/447
Progress: 430/447
Progress: 440/447

In [13]:
downtrends_ = downtrends[downtrends['downtrend_score'] >=  10]

In [14]:
downtrends_

,symbol,trend,score,uptrend_score,downtrend_score,current_price,price_change_5,price_change_10,rsi,volume_ratio,...,down_sma10_below_sma20,down_ema_bearish,down_rsi_bearish,down_macd_bearish,down_volume_decreasing_or_panic,down_lower_highs,down_below_bb_middle,down_momentum_weak,down_momentum_5_negative,down_momentum_10_negative
443,ZKJUSDT,DOWNTREND,11.0,0.0,11.0,0.164100,-1.14,-1.62,35.56,0.66,...,True,True,True,True,True,True,True,True,True,True
418,VOXELUSDT,DOWNTREND,11.0,0.0,11.0,0.051000,-0.78,-1.54,18.52,0.55,...,True,True,True,True,True,True,True,True,True,True
26,AGTUSDT,DOWNTREND,11.0,0.0,11.0,0.009445,-0.20,-1.38,33.15,0.48,...,True,True,True,True,True,True,True,True,True,True
403,TUTUSDT,DOWNTREND,11.0,0.0,11.0,0.062740,-0.40,-0.96,24.58,0.78,...,True,True,True,True,True,True,True,True,True,True
349,SFPUSDT,DOWNTREND,11.0,1.0,11.0,0.473600,-0.25,-0.23,40.54,0.01,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,MTLUSDT,DOWNTREND,10.0,2.0,10.0,0.711000,-0.42,0.14,45.45,0.05,...,True,True,True,True,True,True,True,True,True,False
138,DUSKUSDT,DOWNTREND,10.0,0.0,10.0,0.058900,-0.67,-0.84,38.71,0.34,...,True,True,True,True,True,False,True,True,True,True
294,ORDIUSDT,DOWNTREND,10.0,1.0,10.0,8.390000,-0.83,-0.12,36.25,0.20,...,True,False,True,True,True,True,True,True,True,True
295,OXTUSDT,DOWNTREND,10.0,0.0,10.0,0.054000,-0.55,-0.18,40.00,0.15,...,True,True,True,True,True,False,True,True,True,True
118,CVCUSDT,DOWNTREND,10.0,1.0,10.0,0.093700,-0.85,-0.43,41.18,0.49,...,True,True,True,True,True,False,True,True,True,True

In [ ]:
perp_longs = get_long_signals(downtrends_['symbol'].to_list(), timeframe='15m', market_type='future')

✅ Initialized for Binance PERPETUAL CONTRACTS

🔍 Scanning 43 coins on FUTURE market...
Scanning FVG opportunities for VELODROMEUSDT (future)...
Scanning FVG opportunities for VICUSDT (future)...
Scanning FVG opportunities for ALPINEUSDT (future)...
Scanning FVG opportunities for ARKUSDT (future)...
Scanning FVG opportunities for BSWUSDT (future)...
Scanning FVG opportunities for CAKEUSDT (future)...
Scanning FVG opportunities for CELOUSDT (future)...
Scanning FVG opportunities for BIDUSDT (future)...
Scanning FVG opportunities for BNBUSDT (future)...
Scanning FVG opportunities for SXTUSDT (future)...
Scanning FVG opportunities for DEXEUSDT (future)...
Scanning FVG opportunities for SIGNUSDT (future)...
Scanning FVG opportunities for SYRUPUSDT (future)...
Scanning FVG opportunities for AVAAIUSDT (future)...
Scanning FVG opportunities for GPSUSDT (future)...
Scanning FVG opportunities for FIDAUSDT (future)...
Scanning FVG opportunities for PENGUUSDT (future)...
Scanning FVG opportunities for PORT3USDT (future)...
Scanning FVG opportunities for PUMPBTCUSDT (future)...
Scanning FVG opportunities for JOEUSDT (future)...
Scanning FVG opportunities for MKRUSDT (future)...
Scanning FVG opportunities for LEVERUSDT (future)...
Scanning FVG opportunities for LPTUSDT (future)...
Scanning FVG opportunities for LINKUSDT (future)...
Scanning FVG opportunities for B3USDT (future)...
Scanning FVG opportunities for BMTUSDT (future)...
Scanning FVG opportunities for ALPHAUSDT (future)...
Scanning FVG opportunities for AKTUSDT (future)...
Scanning FVG opportunities for SLERFUSDT (future)...
Scanning FVG opportunities for THEUSDT (future)...
Scanning FVG opportunities for IOTXUSDT (future)...
Scanning FVG opportunities for IDOLUSDT (future)...
Scanning FVG opportunities for AERGOUSDT (future)...
Scanning FVG opportunities for JSTUSDT (future)...
Scanning FVG opportunities for PUNDIXUSDT (future)...
Scanning FVG opportunities for OBOLUSDT (future)...
Scanning FVG opportunities for ORCAUSDT (future)...
Scanning FVG opportunities for ARPAUSDT (future)...
Scanning FVG opportunities for USTCUSDT (future)...
Scanning FVG opportunities for HYPEUSDT (future)...
Scanning FVG opportunities for PLUMEUSDT (future)...
Scanning FVG opportunities for ASRUSDT (future)...
Scanning FVG opportunities for 1000BONKUSDT (future)...

In [ ]:
perp_longs

Empty DataFrame
Columns: []
Index: []

In [15]:
both_markets_df = get_binance_buy_sell_pressure(
    symbols=active_symbols,
    include_both_markets=True,  # Both spot and perpetual
    apply_filters=True,
    top_n=20
)

Error fetching spot data for 1000BONKUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000BONKUSDT&interval=1h&limit=20
Error fetching spot data for 1000000BOBUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000000BOBUSDT&interval=1h&limit=20
Error fetching spot data for 1000000MOGUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000000MOGUSDT&interval=1h&limit=20
Error fetching spot data for 1000PEPEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000PEPEUSDT&interval=1h&limit=20
Error fetching spot data for 1000RATSUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000RATSUSDT&interval=1h&limit=20
Error fetching spot data for 1000FLOKIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000FLOKIUSDT&interval=1h&limit=20
Error fetching spot data for 1000LUNCUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000LUNCUSDT&interval=1h&limit=20
Error fetching spot data for 1000SHIBUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000SHIBUSDT&interval=1h&limit=20
Error fetching spot data for 1000WHYUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000WHYUSDT&interval=1h&limit=20
Error fetching spot data for 1000XUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000XUSDT&interval=1h&limit=20
Error fetching spot data for 1000XECUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=1000XECUSDT&interval=1h&limit=20
Error fetching spot data for AEROUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AEROUSDT&interval=1h&limit=20
Error fetching spot data for AI16ZUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AI16ZUSDT&interval=1h&limit=20
Error fetching spot data for AGTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AGTUSDT&interval=1h&limit=20
Error fetching spot data for AIOTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AIOTUSDT&interval=1h&limit=20
Error fetching spot data for ALCHUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ALCHUSDT&interval=1h&limit=20
Error fetching spot data for AKTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AKTUSDT&interval=1h&limit=20
Error fetching spot data for ARCUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ARCUSDT&interval=1h&limit=20
Error fetching spot data for ATHUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ATHUSDT&interval=1h&limit=20
Error fetching spot data for B2USDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=B2USDT&interval=1h&limit=20
Error fetching spot data for B3USDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=B3USDT&interval=1h&limit=20
Error fetching spot data for AVAAIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=AVAAIUSDT&interval=1h&limit=20
Error fetching spot data for BANKUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BANKUSDT&interval=1h&limit=20
Error fetching spot data for BANUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BANUSDT&interval=1h&limit=20
Error fetching spot data for BIDUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BIDUSDT&interval=1h&limit=20
Error fetching spot data for BDXNUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BDXNUSDT&interval=1h&limit=20
Error fetching spot data for BRETTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BRETTUSDT&interval=1h&limit=20
Error fetching spot data for BROCCOLIF3BUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BROCCOLIF3BUSDT&interval=1h&limit=20
Error fetching spot data for BRUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BRUSDT&interval=1h&limit=20
Error fetching spot data for BTCDOMUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BTCDOMUSDT&interval=1h&limit=20
Error fetching spot data for BUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BUSDT&interval=1h&limit=20
Error fetching spot data for BULLAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BULLAUSDT&interval=1h&limit=20
Error fetching spot data for BSVUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=BSVUSDT&interval=1h&limit=20
Error fetching spot data for CHILLGUYUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=CHILLGUYUSDT&interval=1h&limit=20
Error fetching spot data for DEEPUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DEEPUSDT&interval=1h&limit=20
Error fetching spot data for DEFIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DEFIUSDT&interval=1h&limit=20
Error fetching spot data for DEGENUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DEGENUSDT&interval=1h&limit=20
Error fetching spot data for DMCUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DMCUSDT&interval=1h&limit=20
Error fetching spot data for DODOXUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DODOXUSDT&interval=1h&limit=20
Error fetching spot data for DOLOUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DOLOUSDT&interval=1h&limit=20
Error fetching spot data for DOODUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DOODUSDT&interval=1h&limit=20
Error fetching spot data for DRIFTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=DRIFTUSDT&interval=1h&limit=20
Error fetching spot data for EPTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=EPTUSDT&interval=1h&limit=20
Error fetching spot data for FARTCOINUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=FARTCOINUSDT&interval=1h&limit=20
Error fetching spot data for ETHWUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ETHWUSDT&interval=1h&limit=20
Error fetching spot data for FHEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=FHEUSDT&interval=1h&limit=20
Error fetching spot data for FUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=FUSDT&interval=1h&limit=20
Error fetching spot data for GOATUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=GOATUSDT&interval=1h&limit=20
Error fetching spot data for GRASSUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=GRASSUSDT&interval=1h&limit=20
Error fetching spot data for GRIFFAINUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=GRIFFAINUSDT&interval=1h&limit=20
Error fetching spot data for HIPPOUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=HIPPOUSDT&interval=1h&limit=20
Error fetching spot data for HUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=HUSDT&interval=1h&limit=20
Error fetching spot data for ICNTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ICNTUSDT&interval=1h&limit=20
Error fetching spot data for IDOLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=IDOLUSDT&interval=1h&limit=20
Error fetching spot data for HYPEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=HYPEUSDT&interval=1h&limit=20
Error fetching spot data for IPUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=IPUSDT&interval=1h&limit=20
Error fetching spot data for JELLYJELLYUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=JELLYJELLYUSDT&interval=1h&limit=20
Error fetching spot data for KASUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=KASUSDT&interval=1h&limit=20
Error fetching spot data for KOMAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=KOMAUSDT&interval=1h&limit=20
Error fetching spot data for LUNA2USDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=LUNA2USDT&interval=1h&limit=20
Error fetching spot data for MAVIAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MAVIAUSDT&interval=1h&limit=20
Error fetching spot data for MEMEFIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MEMEFIUSDT&interval=1h&limit=20
Error fetching spot data for MERLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MERLUSDT&interval=1h&limit=20
Error fetching spot data for MEWUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MEWUSDT&interval=1h&limit=20
Error fetching spot data for MELANIAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MELANIAUSDT&interval=1h&limit=20
Error fetching spot data for MILKUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MILKUSDT&interval=1h&limit=20
Error fetching spot data for MOCAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MOCAUSDT&interval=1h&limit=20
Error fetching spot data for MOODENGUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MOODENGUSDT&interval=1h&limit=20
Error fetching spot data for MORPHOUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MORPHOUSDT&interval=1h&limit=20
Error fetching spot data for MYXUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MYXUSDT&interval=1h&limit=20
Error fetching spot data for MYROUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MYROUSDT&interval=1h&limit=20
Error fetching spot data for MUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=MUSDT&interval=1h&limit=20
Error fetching spot data for NEIROETHUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=NEIROETHUSDT&interval=1h&limit=20
Error fetching spot data for OBOLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=OBOLUSDT&interval=1h&limit=20
Error fetching spot data for OLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=OLUSDT&interval=1h&limit=20
Error fetching spot data for PIPPINUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PIPPINUSDT&interval=1h&limit=20
Error fetching spot data for PLUMEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PLUMEUSDT&interval=1h&limit=20
Error fetching spot data for PONKEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PONKEUSDT&interval=1h&limit=20
Error fetching spot data for POPCATUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=POPCATUSDT&interval=1h&limit=20
Error fetching spot data for PORT3USDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PORT3USDT&interval=1h&limit=20
Error fetching spot data for PROMPTUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PROMPTUSDT&interval=1h&limit=20
Error fetching spot data for PUFFERUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PUFFERUSDT&interval=1h&limit=20
Error fetching spot data for PUMPBTCUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PUMPBTCUSDT&interval=1h&limit=20
Error fetching spot data for PUMPUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=PUMPUSDT&interval=1h&limit=20
Error fetching spot data for RAYSOLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=RAYSOLUSDT&interval=1h&limit=20
Error fetching spot data for SAFEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SAFEUSDT&interval=1h&limit=20
Error fetching spot data for SIRENUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SIRENUSDT&interval=1h&limit=20
Error fetching spot data for SKATEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SKATEUSDT&interval=1h&limit=20
Error fetching spot data for SKYAIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SKYAIUSDT&interval=1h&limit=20
Error fetching spot data for SLERFUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SLERFUSDT&interval=1h&limit=20
Error fetching spot data for SONICUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SONICUSDT&interval=1h&limit=20
Error fetching spot data for SOONUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SOONUSDT&interval=1h&limit=20
Error fetching spot data for SQDUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SQDUSDT&interval=1h&limit=20
Error fetching spot data for SPXUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SPXUSDT&interval=1h&limit=20
Error fetching spot data for SWARMSUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SWARMSUSDT&interval=1h&limit=20
Error fetching spot data for SWELLUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=SWELLUSDT&interval=1h&limit=20
Error fetching spot data for TANSSIUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=TANSSIUSDT&interval=1h&limit=20
Error fetching spot data for TAIKOUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=TAIKOUSDT&interval=1h&limit=20
Error fetching spot data for TOKENUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=TOKENUSDT&interval=1h&limit=20
Error fetching spot data for UXLINKUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=UXLINKUSDT&interval=1h&limit=20
Error fetching spot data for VINEUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=VINEUSDT&interval=1h&limit=20
Error fetching spot data for VVVUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=VVVUSDT&interval=1h&limit=20
Error fetching spot data for WALUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=WALUSDT&interval=1h&limit=20
Error fetching spot data for XCNUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=XCNUSDT&interval=1h&limit=20
Error fetching spot data for ZKJUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ZKJUSDT&interval=1h&limit=20
Error fetching spot data for ZEREBROUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ZEREBROUSDT&interval=1h&limit=20
Error fetching spot data for ZETAUSDT: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/klines?symbol=ZETAUSDT&interval=1h&limit=20

In [16]:
both_markets_df

,rank,symbol,market_type,current_buy_pressure,current_sell_pressure,avg_buy_pressure_5periods,buy_pressure_trend,latest_price_change,latest_volume,volume_trend,volatility,timestamp,signal,momentum
0,1,BNBUSDT,spot,73.73,26.27,63.80,1.47,0.10,13396.398,38.07,0.34,2025-07-10T17:46:22.371419,BUY,EXPLOSIVE
1,2,MOVEUSDT,spot,65.33,34.67,63.08,-0.59,-0.21,1769788.300,0.81,0.86,2025-07-10T17:46:25.331180,AVOID,BUILDING
2,3,PROMUSDT,spot,72.60,27.40,63.03,4.22,0.28,4785.510,21.65,0.66,2025-07-10T17:46:26.499023,BUY,EXPLOSIVE
3,4,SXTUSDT,spot,80.49,19.51,62.10,5.70,0.77,4519649.800,15.85,2.19,2025-07-10T17:46:27.496994,STRONG_BUY,EXPLOSIVE
4,5,AEVOUSDT,spot,70.46,29.54,62.06,-1.19,0.44,225928.600,1.56,1.07,2025-07-10T17:46:21.278998,AVOID,GOOD
5,6,COSUSDT,perpetual,55.85,44.15,62.02,-3.00,0.23,8810839.000,15.15,0.64,2025-07-10T17:46:22.898631,AVOID,STRONG
6,7,SFPUSDT,spot,66.39,33.61,61.35,8.26,-0.27,37197.000,621.31,0.59,2025-07-10T17:46:26.971508,BUY,EXPLOSIVE
7,8,BCHUSDT,spot,60.32,39.68,61.28,0.26,0.47,2536.077,28.35,0.60,2025-07-10T17:46:22.200142,WATCH,STRONG
8,9,ASRUSDT,spot,70.43,29.57,60.39,9.59,0.62,10925.700,43.09,0.53,2025-07-10T17:46:21.822776,BUY,EXPLOSIVE
9,10,MEUSDT,spot,54.21,45.79,60.29,-4.90,0.26,11824.080,20.57,0.63,2025-07-10T17:46:25.139807,AVOID,STRONG
10,11,USDCUSDT,perpetual,74.56,25.44,60.11,2.14,-0.00,365389.000,103.03,0.00,2025-07-10T17:46:27.920338,BUY,EXPLOSIVE
11,12,RENDERUSDT,spot,53.62,46.38,59.90,-1.78,0.82,110262.060,38.70,1.05,2025-07-10T17:46:26.692978,AVOID,STRONG
12,13,B2USDT,perpetual,55.54,44.46,59.60,0.20,0.29,95783.000,-39.41,1.14,2025-07-10T17:46:22.069576,AVOID,BUILDING
13,14,FORTHUSDT,spot,68.91,31.09,59.52,6.42,0.57,67778.730,179.08,0.79,2025-07-10T17:46:23.718388,BUY,EXPLOSIVE
14,15,TWTUSDT,perpetual,62.14,37.86,59.49,2.83,0.19,95361.000,422.12,1.32,2025-07-10T17:46:27.869007,BUY,EXPLOSIVE
15,16,KAVAUSDT,spot,55.08,44.92,59.37,-1.89,-0.30,159049.200,110.70,0.51,2025-07-10T17:46:24.646865,AVOID,GOOD
16,17,THETAUSDT,spot,62.60,37.40,59.15,1.84,0.13,46165.800,-28.24,0.94,2025-07-10T17:46:27.625852,AVOID,GOOD
17,18,ACHUSDT,spot,40.52,59.48,58.75,-8.71,-0.15,2076577.000,-3.35,0.80,2025-07-10T17:46:21.178877,AVOID,BUILDING
18,19,XTZUSDT,spot,60.73,39.27,58.39,-3.08,0.35,78993.600,31.52,0.71,2025-07-10T17:46:28.378701,AVOID,STRONG
19,20,BERAUSDT,spot,46.81,53.19,58.14,-1.75,0.82,65136.070,44.80,1.46,2025-07-10T17:46:22.420137,AVOID,STRONG

In [17]:
scanner = Binance_Support_Resistance_Perpetual_Scanner()

In [18]:
results = scanner.scan_multiple_coins(active_symbols)

Scanning 1000000BOBUSDT...
Scanning 1000000MOGUSDT...
Scanning 1000BONKUSDT...
Scanning 1000CATUSDT...
Scanning 1000CHEEMSUSDT...
Scanning 1000FLOKIUSDT...
Scanning 1000LUNCUSDT...
Scanning 1000PEPEUSDT...
Scanning 1000RATSUSDT...
Scanning 1000SATSUSDT...
Scanning 1000SHIBUSDT...
Scanning 1000WHYUSDT...
Scanning 1000XECUSDT...
Scanning 1000XUSDT...
Scanning 1INCHUSDT...
Scanning 1MBABYDOGEUSDT...
Scanning AAVEUSDT...
Scanning ACEUSDT...
Scanning ACHUSDT...
Scanning ACTUSDT...
Scanning ACXUSDT...
Scanning ADAUSDT...
Scanning AERGOUSDT...
Scanning AEROUSDT...
Scanning AEVOUSDT...
Scanning AGLDUSDT...
Scanning AGTUSDT...
Scanning AI16ZUSDT...
Scanning AIOTUSDT...
Scanning AIUSDT...
Scanning AIXBTUSDT...
Scanning AKTUSDT...
Scanning ALCHUSDT...
Scanning ALGOUSDT...
Scanning ALICEUSDT...
Scanning ALPHAUSDT...
Scanning ALPINEUSDT...
Scanning ALTUSDT...
Scanning ANIMEUSDT...
Scanning ANKRUSDT...
Scanning APEUSDT...
Scanning API3USDT...
Scanning APTUSDT...
Scanning ARBUSDT...
Scanning ARCUSDT...
Scanning ARKMUSDT...
Scanning ARKUSDT...
Scanning ARPAUSDT...
Scanning ARUSDT...
Scanning ASRUSDT...
Scanning ASTRUSDT...
Scanning ATAUSDT...
Scanning ATHUSDT...
Scanning ATOMUSDT...
Scanning AUCTIONUSDT...
Scanning AUSDT...
Scanning AVAAIUSDT...
Scanning AVAUSDT...
Scanning AVAXUSDT...
Scanning AWEUSDT...
Scanning AXLUSDT...
Scanning AXSUSDT...
Scanning B2USDT...
Scanning B3USDT...
Scanning BABYUSDT...
Scanning BAKEUSDT...
Scanning BANANAS31USDT...
Scanning BANANAUSDT...
Scanning BANDUSDT...
Scanning BANKUSDT...
Scanning BANUSDT...
Scanning BATUSDT...
Scanning BBUSDT...
Scanning BCHUSDT...
Scanning BDXNUSDT...
Scanning BEAMXUSDT...
Scanning BELUSDT...
Scanning BERAUSDT...
Scanning BICOUSDT...
Scanning BIDUSDT...
Scanning BIGTIMEUSDT...
Scanning BIOUSDT...
Scanning BLURUSDT...
Scanning BMTUSDT...
Scanning BNBUSDT...
Scanning BNTUSDT...
Scanning BOMEUSDT...
Scanning BRETTUSDT...
Scanning BROCCOLI714USDT...
Scanning BROCCOLIF3BUSDT...
Scanning BRUSDT...
Scanning BSVUSDT...
Scanning BSWUSDT...
Scanning BTCDOMUSDT...
Scanning BTCUSDT...
Scanning BULLAUSDT...
Scanning BUSDT...
Scanning C98USDT...
Scanning CAKEUSDT...
Scanning CATIUSDT...
Scanning CELOUSDT...
Scanning CELRUSDT...
Scanning CETUSUSDT...
Scanning CFXUSDT...
Scanning CGPTUSDT...
Scanning CHESSUSDT...
Scanning CHILLGUYUSDT...
Scanning CHRUSDT...
Scanning CHZUSDT...
Scanning CKBUSDT...
Scanning COMPUSDT...
Scanning COOKIEUSDT...
Scanning COSUSDT...
Scanning COTIUSDT...
Scanning COWUSDT...
Scanning CRVUSDT...
Scanning CTKUSDT...
Scanning CTSIUSDT...
Scanning CVCUSDT...
Scanning CYBERUSDT...
Scanning DASHUSDT...
Scanning DEEPUSDT...
Scanning DEFIUSDT...
Scanning DEGENUSDT...
Scanning DEGOUSDT...
Scanning DENTUSDT...
Scanning DEXEUSDT...
Scanning DFUSDT...
Scanning DIAUSDT...
Scanning DMCUSDT...
Scanning DODOXUSDT...
Scanning DOGEUSDT...
Scanning DOGSUSDT...
Scanning DOLOUSDT...
Scanning DOODUSDT...
Scanning DOTUSDT...
Scanning DRIFTUSDT...
Scanning DUSDT...
Scanning DUSKUSDT...
Scanning DYDXUSDT...
Scanning DYMUSDT...
Scanning EDUUSDT...
Scanning EGLDUSDT...
Scanning EIGENUSDT...
Scanning ENAUSDT...
Scanning ENJUSDT...
Scanning ENSUSDT...
Scanning EPICUSDT...
Scanning EPTUSDT...
Scanning ETCUSDT...
Scanning ETHFIUSDT...
Scanning ETHUSDT...
Scanning ETHWUSDT...
Scanning FARTCOINUSDT...
Scanning FETUSDT...
Scanning FHEUSDT...
Scanning FIDAUSDT...
Scanning FILUSDT...
Scanning FIOUSDT...
Scanning FISUSDT...
Scanning FLMUSDT...
Scanning FLOWUSDT...
Scanning FLUXUSDT...
Scanning FORMUSDT...
Scanning FORTHUSDT...
Scanning FUNUSDT...
Scanning FUSDT...
Scanning FXSUSDT...
Scanning GALAUSDT...
Scanning GASUSDT...
Scanning GHSTUSDT...
Scanning GLMUSDT...
Scanning GMTUSDT...
Scanning GMXUSDT...
Scanning GOATUSDT...
Scanning GPSUSDT...
Scanning GRASSUSDT...
Scanning GRIFFAINUSDT...
Scanning GRTUSDT...
Scanning GTCUSDT...
Scanning GUNUSDT...
Scanning GUSDT...
Scanning HAEDALUSDT...
Scanning HBARUSDT...
Scanning HEIUSDT...
Scanning HFTUSDT...
Scanning HIFIUSDT...
Scanning HIGHUSDT...
Scanning HIPPOUSDT...
Scanning HIVEUSDT...
Scanning HMSTRUSDT...
Scanning HOMEUSDT...
Scanning HOOKUSDT...
Scanning HOTUSDT...
Scanning HUMAUSDT...
Scanning HUSDT...
Scanning HYPERUSDT...
Scanning HYPEUSDT...
Scanning ICNTUSDT...
Scanning ICPUSDT...
Scanning ICXUSDT...
Scanning IDOLUSDT...
Scanning IDUSDT...
Scanning ILVUSDT...
Scanning IMXUSDT...
Scanning INITUSDT...
Scanning INJUSDT...
Scanning IOSTUSDT...
Scanning IOTAUSDT...
Scanning IOTXUSDT...
Scanning IOUSDT...
Scanning IPUSDT...
Scanning JASMYUSDT...
Scanning JELLYJELLYUSDT...
Scanning JOEUSDT...
Scanning JSTUSDT...
Scanning JTOUSDT...
Scanning JUPUSDT...
Scanning KAIAUSDT...
Scanning KAITOUSDT...
Scanning KASUSDT...
Scanning KAVAUSDT...
Scanning KDAUSDT...
Scanning KERNELUSDT...
Scanning KMNOUSDT...
Scanning KNCUSDT...
Scanning KOMAUSDT...
Scanning KSMUSDT...
Scanning LAUSDT...
Scanning LAYERUSDT...
Scanning LDOUSDT...
Scanning LEVERUSDT...
Scanning LINKUSDT...
Scanning LISTAUSDT...
Scanning LOKAUSDT...
Scanning LPTUSDT...
Scanning LQTYUSDT...
Scanning LRCUSDT...
Scanning LSKUSDT...
Scanning LTCUSDT...
Scanning LUMIAUSDT...
Scanning LUNA2USDT...
Scanning MAGICUSDT...
Scanning MANAUSDT...
Scanning MANTAUSDT...
Scanning MASKUSDT...
Scanning MAVIAUSDT...
Scanning MAVUSDT...
Scanning MBOXUSDT...
Scanning MELANIAUSDT...
Scanning MEMEFIUSDT...
Scanning MEMEUSDT...
Scanning MERLUSDT...
Scanning METISUSDT...
Scanning MEUSDT...
Scanning MEWUSDT...
Scanning MILKUSDT...
Scanning MINAUSDT...
Scanning MKRUSDT...
Scanning MLNUSDT...
Scanning MOCAUSDT...
Scanning MOODENGUSDT...
Scanning MORPHOUSDT...
Scanning MOVEUSDT...
Scanning MOVRUSDT...
Scanning MTLUSDT...
Scanning MUBARAKUSDT...
Scanning MUSDT...
Scanning MYROUSDT...
Scanning MYXUSDT...
Scanning NEARUSDT...
Scanning NEIROETHUSDT...
Scanning NEIROUSDT...
Scanning NEOUSDT...
Scanning NEWTUSDT...
Scanning NFPUSDT...
Scanning NILUSDT...
Scanning NKNUSDT...
Scanning NMRUSDT...
Scanning NOTUSDT...
Scanning NTRNUSDT...
Scanning NXPCUSDT...
Scanning OBOLUSDT...
Scanning OGNUSDT...
Scanning OGUSDT...
Scanning OLUSDT...
Scanning OMNIUSDT...
Scanning OMUSDT...
Scanning ONDOUSDT...
Scanning ONEUSDT...
Scanning ONGUSDT...
Scanning ONTUSDT...
Scanning OPUSDT...
Scanning ORCAUSDT...
Scanning ORDIUSDT...
Scanning OXTUSDT...
Scanning PARTIUSDT...
Scanning PAXGUSDT...
Scanning PENDLEUSDT...
Scanning PENGUUSDT...
Scanning PEOPLEUSDT...
Scanning PERPUSDT...
Scanning PHAUSDT...
Scanning PHBUSDT...
Scanning PIPPINUSDT...
Scanning PIXELUSDT...
Scanning PLUMEUSDT...
Scanning PNUTUSDT...
Scanning POLUSDT...
Scanning POLYXUSDT...
Scanning PONKEUSDT...
Scanning POPCATUSDT...
Scanning PORT3USDT...
Scanning PORTALUSDT...
Scanning POWRUSDT...
Scanning PROMPTUSDT...
Scanning PROMUSDT...
Scanning PUFFERUSDT...
Scanning PUMPBTCUSDT...
Scanning PUMPUSDT...
Scanning PUNDIXUSDT...
Scanning PYTHUSDT...
Scanning QNTUSDT...
Scanning QTUMUSDT...
Scanning QUICKUSDT...
Scanning RAREUSDT...
Scanning RAYSOLUSDT...
Scanning RDNTUSDT...
Scanning REDUSDT...
Scanning REIUSDT...
Scanning RENDERUSDT...
Scanning RESOLVUSDT...
Scanning REZUSDT...
Scanning RIFUSDT...
Scanning RLCUSDT...
Scanning RONINUSDT...
Scanning ROSEUSDT...
Scanning RPLUSDT...
Scanning RSRUSDT...
Scanning RUNEUSDT...
Scanning RVNUSDT...
Scanning SAFEUSDT...
Scanning SAGAUSDT...
Scanning SAHARAUSDT...
Scanning SANDUSDT...
Scanning SANTOSUSDT...
Scanning SCRTUSDT...
Scanning SCRUSDT...
Scanning SEIUSDT...
Scanning SFPUSDT...
Scanning SHELLUSDT...
Scanning SIGNUSDT...
Scanning SIRENUSDT...
Scanning SKATEUSDT...
Scanning SKLUSDT...
Scanning SKYAIUSDT...
Scanning SLERFUSDT...
Scanning SNXUSDT...
Scanning SOLUSDT...
Scanning SOLVUSDT...
Scanning SONICUSDT...
Scanning SOONUSDT...
Scanning SOPHUSDT...
Scanning SPELLUSDT...
Scanning SPKUSDT...
Scanning SPXUSDT...
Scanning SQDUSDT...
Scanning SSVUSDT...
Scanning STEEMUSDT...
Scanning STGUSDT...
Scanning STORJUSDT...
Scanning STOUSDT...
Scanning STRKUSDT...
Scanning STXUSDT...
Scanning SUIUSDT...
Scanning SUNUSDT...
Scanning SUPERUSDT...
Scanning SUSDT...
Scanning SUSHIUSDT...
Scanning SWARMSUSDT...
Scanning SWELLUSDT...
Scanning SXPUSDT...
Scanning SXTUSDT...
Scanning SYNUSDT...
Scanning SYRUPUSDT...
Scanning SYSUSDT...
Scanning TAIKOUSDT...
Scanning TANSSIUSDT...
Scanning TAOUSDT...
Scanning THETAUSDT...
Scanning THEUSDT...
Scanning TIAUSDT...
Scanning TLMUSDT...
Scanning TNSRUSDT...
Scanning TOKENUSDT...
Scanning TONUSDT...
Scanning TRBUSDT...
Scanning TRUMPUSDT...
Scanning TRUUSDT...
Scanning TRXUSDT...
Scanning TSTUSDT...
Scanning TURBOUSDT...
Scanning TUSDT...
Scanning TUTUSDT...
Scanning TWTUSDT...
Scanning UMAUSDT...
Scanning UNIUSDT...
Scanning USDCUSDT...
Scanning USTCUSDT...
Scanning USUALUSDT...
Scanning UXLINKUSDT...
Scanning VANAUSDT...
Scanning VANRYUSDT...
Scanning VELODROMEUSDT...
Scanning VETUSDT...
Scanning VICUSDT...
Scanning VINEUSDT...
Scanning VIRTUALUSDT...
Scanning VOXELUSDT...
Scanning VTHOUSDT...
Scanning VVVUSDT...
Scanning WALUSDT...
Scanning WAXPUSDT...
Scanning WCTUSDT...
Scanning WIFUSDT...
Scanning WLDUSDT...
Scanning WOOUSDT...
Scanning WUSDT...
Scanning XAIUSDT...
Scanning XCNUSDT...
Scanning XLMUSDT...
Scanning XMRUSDT...
Scanning XRPUSDT...
Scanning XTZUSDT...
Scanning XVGUSDT...
Scanning XVSUSDT...
Scanning YFIUSDT...
Scanning YGGUSDT...
Scanning ZECUSDT...
Scanning ZENUSDT...
Scanning ZEREBROUSDT...
Scanning ZETAUSDT...
Scanning ZILUSDT...
Scanning ZKJUSDT...
Scanning ZKUSDT...
Scanning ZROUSDT...
Scanning ZRXUSDT...

In [21]:
results = pd.DataFrame(results)
results

,symbol,current_price,signal,rsi,change_24h,volume_24h,quote_volume_24h,near_support,support_level,support_strength,near_resistance,resistance_level,resistance_strength,total_support_levels,total_resistance_levels,poc_price,near_poc,contract_type
0,1000000BOBUSDT,0.081960,NEUTRAL,65.83,5.30,1.597777e+09,1.202929e+08,False,NaN,0,False,NaN,0,1,3,0.064846,False,PERPETUAL
1,1000000MOGUSDT,1.280800,NEUTRAL,75.64,11.31,3.108043e+07,3.695668e+07,False,NaN,0,False,NaN,0,3,2,1.049662,False,PERPETUAL
2,1000BONKUSDT,0.022543,NEUTRAL,75.88,4.47,3.297171e+10,6.931709e+08,False,NaN,0,False,NaN,0,2,2,0.022189,False,PERPETUAL
3,1000CATUSDT,0.007515,NEUTRAL,79.43,7.93,8.608555e+08,6.245932e+06,False,NaN,0,False,NaN,0,2,2,0.007009,False,PERPETUAL
4,1000CHEEMSUSDT,0.001351,NEUTRAL,60.20,-0.04,5.297095e+09,7.133237e+06,False,NaN,0,False,NaN,0,3,3,0.001444,False,PERPETUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,ZILUSDT,0.011360,RESISTANCE,68.42,3.93,9.642790e+08,1.074175e+07,False,NaN,0,True,0.01132,12,3,2,0.010367,False,PERPETUAL
443,ZKJUSDT,0.167500,NEUTRAL,74.39,4.10,7.409823e+07,1.209125e+07,False,NaN,0,False,NaN,0,3,3,0.171102,False,PERPETUAL
444,ZKUSDT,0.049820,NEUTRAL,76.68,7.39,2.109029e+08,1.011816e+07,False,NaN,0,False,NaN,0,2,2,0.045289,False,PERPETUAL
445,ZROUSDT,1.946800,NEUTRAL,68.37,6.66,1.121911e+07,2.122371e+07,False,NaN,0,False,NaN,0,3,2,1.790303,False,PERPETUAL
446,ZRXUSDT,0.235500,NEUTRAL,67.42,3.84,7.283417e+07,1.685609e+07,False,NaN,0,False,NaN,0,3,2,0.227090,False,PERPETUAL

In [25]:
results[results['signal'] == 'NEUTRAL']

,symbol,current_price,signal,rsi,change_24h,volume_24h,quote_volume_24h,near_support,support_level,support_strength,near_resistance,resistance_level,resistance_strength,total_support_levels,total_resistance_levels,poc_price,near_poc,contract_type
0,1000000BOBUSDT,0.081960,NEUTRAL,65.83,5.30,1.597777e+09,1.202929e+08,False,NaN,0,False,NaN,0,1,3,0.064846,False,PERPETUAL
1,1000000MOGUSDT,1.280800,NEUTRAL,75.64,11.31,3.108043e+07,3.695668e+07,False,NaN,0,False,NaN,0,3,2,1.049662,False,PERPETUAL
2,1000BONKUSDT,0.022543,NEUTRAL,75.88,4.47,3.297171e+10,6.931709e+08,False,NaN,0,False,NaN,0,2,2,0.022189,False,PERPETUAL
3,1000CATUSDT,0.007515,NEUTRAL,79.43,7.93,8.608555e+08,6.245932e+06,False,NaN,0,False,NaN,0,2,2,0.007009,False,PERPETUAL
4,1000CHEEMSUSDT,0.001351,NEUTRAL,60.20,-0.04,5.297095e+09,7.133237e+06,False,NaN,0,False,NaN,0,3,3,0.001444,False,PERPETUAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,ZEREBROUSDT,0.031640,NEUTRAL,62.47,19.49,5.911532e+09,2.096802e+08,False,NaN,0,False,NaN,0,3,3,0.034479,False,PERPETUAL
443,ZKJUSDT,0.167500,NEUTRAL,74.39,4.10,7.409823e+07,1.209125e+07,False,NaN,0,False,NaN,0,3,3,0.171102,False,PERPETUAL
444,ZKUSDT,0.049820,NEUTRAL,76.68,7.39,2.109029e+08,1.011816e+07,False,NaN,0,False,NaN,0,2,2,0.045289,False,PERPETUAL
445,ZROUSDT,1.946800,NEUTRAL,68.37,6.66,1.121911e+07,2.122371e+07,False,NaN,0,False,NaN,0,3,2,1.790303,False,PERPETUAL
446,ZRXUSDT,0.235500,NEUTRAL,67.42,3.84,7.283417e+07,1.685609e+07,False,NaN,0,False,NaN,0,3,2,0.227090,False,PERPETUAL

Modify Chandlier zldma

In [3]:
"""
🧪 LIVE BINANCE DATA STOP LOSS & TAKE PROFIT TEST SUITE
Test the fixed SL/TP logic with REAL market data from Binance
"""

import time
import requests
from datetime import datetime

class LiveTrade:
    """Live trade object using real Binance data"""
    def __init__(self, symbol, side, margin_amount, leverage):
        self.symbol = symbol
        self.side = side
        self.margin_amount = margin_amount
        self.leverage = leverage
        
        # Get live market data
        self.entry_price = self.get_current_price()
        self.quantity = (margin_amount * leverage) / self.entry_price
        
        # Calculate realistic SL/TP levels
        if side == "long":
            self.stop_loss = self.entry_price * 0.97    # 3% stop loss
            self.take_profit = self.entry_price * 1.06  # 6% take profit
        else:  # short
            self.stop_loss = self.entry_price * 1.03    # 3% stop loss
            self.take_profit = self.entry_price * 0.94  # 6% take profit
            
        self.failed_checks = 0
        self.last_price_check = self.entry_price
        self.trade_id = f"LIVE_{symbol}_{int(time.time())}"
        
        print(f"📊 Created LIVE {side.upper()} trade for {symbol}")
        print(f"   Entry: ${self.entry_price:.6f}")
        print(f"   Stop Loss: ${self.stop_loss:.6f}")
        print(f"   Take Profit: ${self.take_profit:.6f}")
        print(f"   Margin: ${margin_amount} | Leverage: {leverage}x")
    
    def get_current_price(self):
        """Get live price from Binance"""
        try:
            url = f"https://fapi.binance.com/fapi/v1/ticker/price"
            params = {'symbol': self.symbol}
            response = requests.get(url, params=params, timeout=5)
            response.raise_for_status()
            data = response.json()
            return float(data['price'])
        except Exception as e:
            print(f"❌ Error getting live price for {self.symbol}: {e}")
            return 0.0

def get_live_binance_prices(symbols, num_samples=5):
    """Fetch multiple live price samples from Binance"""
    print(f"📡 Fetching {num_samples} live price samples from Binance...")
    
    price_samples = {}
    
    for symbol in symbols:
        price_samples[symbol] = []
        
        for i in range(num_samples):
            try:
                url = f"https://fapi.binance.com/fapi/v1/ticker/price"
                params = {'symbol': symbol}
                response = requests.get(url, params=params, timeout=5)
                response.raise_for_status()
                data = response.json()
                price = float(data['price'])
                price_samples[symbol].append(price)
                
                print(f"   {symbol} Sample {i+1}: ${price:.6f}")
                time.sleep(0.2)  # Small delay between requests
                
            except Exception as e:
                print(f"❌ Error fetching {symbol} sample {i+1}: {e}")
    
    return price_samples

def test_live_stop_loss_logic():
    """Test stop loss logic with LIVE Binance data"""
    
    print("🔥 TESTING STOP LOSS LOGIC WITH LIVE BINANCE DATA")
    print("=" * 60)
    
    # Test with live trades
    live_symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
    
    for symbol in live_symbols:
        print(f"\n📊 Testing LIVE {symbol} Data")
        print("-" * 40)
        
        try:
            # Create live long and short trades
            long_trade = LiveTrade(symbol, "long", 100, 5)
            short_trade = LiveTrade(symbol, "short", 100, 5)
            
            # Get multiple live price samples
            live_prices = get_live_binance_prices([symbol], 3)
            
            if symbol not in live_prices or not live_prices[symbol]:
                print(f"❌ No live prices available for {symbol}")
                continue
                
            print(f"\n🔥 Testing LONG position SL logic:")
            for i, current_price in enumerate(live_prices[symbol]):
                # Simulate price movements for testing
                test_prices = [
                    current_price * 0.96,  # 4% drop - should trigger SL
                    current_price * 0.97,  # 3% drop - at SL level
                    current_price * 0.98,  # 2% drop - should not trigger
                    current_price * 1.00,  # no change - should not trigger
                ]
                
                for test_price in test_prices:
                    try:
                        result = self_monitoring_trader._should_trigger_stop_loss_fixed(long_trade, test_price)
                        
                        # Determine expected result
                        price_change_pct = ((test_price - long_trade.entry_price) / long_trade.entry_price) * 100
                        expected = test_price <= long_trade.stop_loss
                        
                        status = "✅" if result == expected else "❌"
                        print(f"   {status} ${test_price:.6f} ({price_change_pct:+.2f}%) - SL: {result}")
                        
                    except Exception as e:
                        print(f"   ❌ Error testing ${test_price:.6f}: {e}")
            
            print(f"\n🔥 Testing SHORT position SL logic:")
            for i, current_price in enumerate(live_prices[symbol]):
                # Simulate price movements for testing
                test_prices = [
                    current_price * 1.04,  # 4% rise - should trigger SL
                    current_price * 1.03,  # 3% rise - at SL level  
                    current_price * 1.02,  # 2% rise - should not trigger
                    current_price * 1.00,  # no change - should not trigger
                ]
                
                for test_price in test_prices:
                    try:
                        result = self_monitoring_trader._should_trigger_stop_loss_fixed(short_trade, test_price)
                        
                        # Determine expected result
                        price_change_pct = ((test_price - short_trade.entry_price) / short_trade.entry_price) * 100
                        expected = test_price >= short_trade.stop_loss
                        
                        status = "✅" if result == expected else "❌"
                        print(f"   {status} ${test_price:.6f} ({price_change_pct:+.2f}%) - SL: {result}")
                        
                    except Exception as e:
                        print(f"   ❌ Error testing ${test_price:.6f}: {e}")
                        
        except Exception as e:
            print(f"❌ Error testing {symbol}: {e}")

def test_live_take_profit_logic():
    """Test take profit logic with LIVE Binance data"""
    
    print("\n\n🎯 TESTING TAKE PROFIT LOGIC WITH LIVE BINANCE DATA")
    print("=" * 60)
    
    # Test with live trades
    live_symbols = ["BTCUSDT", "ETHUSDT", "ADAUSDT"]
    
    for symbol in live_symbols:
        print(f"\n📊 Testing LIVE {symbol} Data")
        print("-" * 40)
        
        try:
            # Create live long and short trades
            long_trade = LiveTrade(symbol, "long", 100, 5)
            short_trade = LiveTrade(symbol, "short", 100, 5)
            
            # Get multiple live price samples
            live_prices = get_live_binance_prices([symbol], 3)
            
            if symbol not in live_prices or not live_prices[symbol]:
                print(f"❌ No live prices available for {symbol}")
                continue
                
            print(f"\n🎯 Testing LONG position TP logic:")
            for current_price in live_prices[symbol]:
                # Simulate price movements for testing
                test_prices = [
                    current_price * 1.04,  # 4% rise - should not trigger yet
                    current_price * 1.06,  # 6% rise - at TP level
                    current_price * 1.07,  # 7% rise - should trigger TP
                    current_price * 1.10,  # 10% rise - should trigger TP
                ]
                
                for test_price in test_prices:
                    try:
                        result = self_monitoring_trader._should_trigger_take_profit_fixed(long_trade, test_price)
                        
                        # Determine expected result
                        price_change_pct = ((test_price - long_trade.entry_price) / long_trade.entry_price) * 100
                        expected = test_price >= long_trade.take_profit
                        
                        status = "✅" if result == expected else "❌"
                        print(f"   {status} ${test_price:.6f} ({price_change_pct:+.2f}%) - TP: {result}")
                        
                    except Exception as e:
                        print(f"   ❌ Error testing ${test_price:.6f}: {e}")
            
            print(f"\n🎯 Testing SHORT position TP logic:")
            for current_price in live_prices[symbol]:
                # Simulate price movements for testing
                test_prices = [
                    current_price * 0.96,  # 4% drop - should not trigger yet
                    current_price * 0.94,  # 6% drop - at TP level
                    current_price * 0.93,  # 7% drop - should trigger TP
                    current_price * 0.90,  # 10% drop - should trigger TP
                ]
                
                for test_price in test_prices:
                    try:
                        result = self_monitoring_trader._should_trigger_take_profit_fixed(short_trade, test_price)
                        
                        # Determine expected result
                        price_change_pct = ((test_price - short_trade.entry_price) / short_trade.entry_price) * 100
                        expected = test_price <= short_trade.take_profit
                        
                        status = "✅" if result == expected else "❌"
                        print(f"   {status} ${test_price:.6f} ({price_change_pct:+.2f}%) - TP: {result}")
                        
                    except Exception as e:
                        print(f"   ❌ Error testing ${test_price:.6f}: {e}")
                        
        except Exception as e:
            print(f"❌ Error testing {symbol}: {e}")

def test_live_precision_edge_cases():
    """Test precision handling with live market prices"""
    
    print("\n\n🔬 TESTING LIVE PRECISION EDGE CASES")
    print("=" * 60)
    
    symbols = ["BTCUSDT", "ETHUSDT", "DOGEUSDT"]  # Different price ranges
    
    for symbol in symbols:
        print(f"\n📊 Precision test for {symbol}")
        print("-" * 40)
        
        try:
            # Create live trade
            trade = LiveTrade(symbol, "long", 50, 5)
            
            # Get current live price
            current_live_price = trade.get_current_price()
            if current_live_price <= 0:
                print(f"❌ Could not get live price for {symbol}")
                continue
            
            print(f"Live Price: ${current_live_price:.8f}")
            print(f"Stop Loss: ${trade.stop_loss:.8f}")
            print(f"Take Profit: ${trade.take_profit:.8f}")
            
            # Test very small price differences around SL/TP levels
            sl_precision_tests = [
                (trade.stop_loss - 0.00001, True, "Just below SL"),
                (trade.stop_loss, True, "Exact SL"),
                (trade.stop_loss + 0.00001, False, "Just above SL"),
            ]
            
            tp_precision_tests = [
                (trade.take_profit - 0.00001, False, "Just below TP"),
                (trade.take_profit, True, "Exact TP"),
                (trade.take_profit + 0.00001, True, "Just above TP"),
            ]
            
            print(f"\n🔬 Stop Loss precision tests:")
            for test_price, expected, description in sl_precision_tests:
                result = self_monitoring_trader._should_trigger_stop_loss_fixed(trade, test_price)
                diff = test_price - trade.stop_loss
                status = "✅" if result == expected else "❌"
                print(f"   {status} ${test_price:.8f} (diff: {diff:+.8f}) - {description}: SL={result}")
            
            print(f"\n🔬 Take Profit precision tests:")
            for test_price, expected, description in tp_precision_tests:
                result = self_monitoring_trader._should_trigger_take_profit_fixed(trade, test_price)
                diff = test_price - trade.take_profit
                status = "✅" if result == expected else "❌"
                print(f"   {status} ${test_price:.8f} (diff: {diff:+.8f}) - {description}: TP={result}")
                
        except Exception as e:
            print(f"❌ Error testing precision for {symbol}: {e}")

def test_live_monitoring_simulation():
    """Simulate the monitoring process with live data"""
    
    print("\n\n🔄 TESTING LIVE MONITORING SIMULATION")
    print("=" * 60)
    
    symbol = "BTCUSDT"  # Use BTC for this test
    
    try:
        print(f"📊 Creating live monitoring simulation for {symbol}")
        
        # Create a live trade
        trade = LiveTrade(symbol, "long", 100, 5)
        
        print(f"\n🤖 Simulating monitoring checks...")
        print(f"Current entry: ${trade.entry_price:.6f}")
        print(f"Stop Loss at: ${trade.stop_loss:.6f}")
        print(f"Take Profit at: ${trade.take_profit:.6f}")
        
        # Simulate 5 monitoring cycles
        for cycle in range(5):
            print(f"\n--- Monitoring Cycle {cycle + 1} ---")
            
            # Get live price
            current_price = trade.get_current_price()
            if current_price <= 0:
                print(f"❌ Could not get price in cycle {cycle + 1}")
                continue
            
            # Calculate price movement
            price_change = ((current_price - trade.entry_price) / trade.entry_price) * 100
            
            print(f"Live Price: ${current_price:.6f} ({price_change:+.3f}%)")
            
            # Test SL/TP logic
            sl_triggered = self_monitoring_trader._should_trigger_stop_loss_fixed(trade, current_price)
            tp_triggered = self_monitoring_trader._should_trigger_take_profit_fixed(trade, current_price)
            
            # Calculate distances
            sl_distance = ((current_price - trade.stop_loss) / current_price) * 100
            tp_distance = ((trade.take_profit - current_price) / current_price) * 100
            
            print(f"SL Distance: {sl_distance:+.3f}% - Triggered: {sl_triggered}")
            print(f"TP Distance: {tp_distance:+.3f}% - Triggered: {tp_triggered}")
            
            # Check if either would trigger
            if sl_triggered:
                print("🚨 STOP LOSS WOULD TRIGGER!")
                break
            elif tp_triggered:
                print("🎯 TAKE PROFIT WOULD TRIGGER!")
                break
            else:
                print("📊 Position continues...")
            
            time.sleep(1)  # Wait 1 second between checks
            
    except Exception as e:
        print(f"❌ Error in monitoring simulation: {e}")

def test_multiple_symbols_live():
    """Test multiple symbols simultaneously with live data"""
    
    print("\n\n🌐 TESTING MULTIPLE SYMBOLS WITH LIVE DATA")
    print("=" * 60)
    
    test_symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "ADAUSDT"]
    live_trades = []
    
    # Create live trades for all symbols
    print("📊 Creating live trades for multiple symbols...")
    for symbol in test_symbols:
        try:
            trade = LiveTrade(symbol, "long", 50, 3)
            live_trades.append(trade)
            time.sleep(0.2)  # Small delay between API calls
        except Exception as e:
            print(f"❌ Error creating trade for {symbol}: {e}")
    
    if not live_trades:
        print("❌ No live trades created")
        return
    
    print(f"\n🔄 Testing {len(live_trades)} live trades simultaneously...")
    
    # Test all trades with current prices
    for trade in live_trades:
        try:
            current_price = trade.get_current_price()
            if current_price <= 0:
                print(f"❌ Could not get price for {trade.symbol}")
                continue
            
            # Test SL/TP logic
            sl_result = self_monitoring_trader._should_trigger_stop_loss_fixed(trade, current_price)
            tp_result = self_monitoring_trader._should_trigger_take_profit_fixed(trade, current_price)
            
            # Calculate performance metrics
            price_change = ((current_price - trade.entry_price) / trade.entry_price) * 100
            sl_distance = ((current_price - trade.stop_loss) / current_price) * 100
            tp_distance = ((trade.take_profit - current_price) / current_price) * 100
            
            print(f"\n📊 {trade.symbol}:")
            print(f"   Price: ${current_price:.6f} ({price_change:+.3f}%)")
            print(f"   SL: {sl_result} (distance: {sl_distance:+.3f}%)")
            print(f"   TP: {tp_result} (distance: {tp_distance:+.3f}%)")
            
        except Exception as e:
            print(f"❌ Error testing {trade.symbol}: {e}")

def test_monitoring_integration():
    """Test the integration with the monitoring system using live data"""
    
    print("\n\n🔄 TESTING MONITORING SYSTEM INTEGRATION")
    print("=" * 60)
    
    # Check if monitoring is active
    try:
        status = self_monitoring_trader.get_monitoring_status()
        print(f"Monitoring Active: {status['monitoring_active']}")
        print(f"Check Interval: {status['check_interval']} seconds")
        print(f"Active Trades: {status['active_trades_count']}")
    except Exception as e:
        print(f"❌ Error getting monitoring status: {e}")
    
    # Test if the fixed methods exist
    methods_to_check = [
        '_should_trigger_stop_loss_fixed',
        '_should_trigger_take_profit_fixed', 
        '_execute_exit_order_fixed',
        '_get_reliable_current_price'
    ]
    
    print("\nChecking fixed methods:")
    for method in methods_to_check:
        exists = hasattr(self_monitoring_trader, method)
        status = "✅" if exists else "❌"
        print(f"{status} {method}")
    
    # Test live price fetching integration
    print(f"\n📡 Testing live price fetching integration:")
    test_symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
    
    for symbol in test_symbols:
        try:
            # Test the trader's price fetching method
            price = self_monitoring_trader._get_reliable_current_price(symbol)
            
            if price > 0:
                print(f"✅ {symbol}: ${price:.6f}")
                
                # Also test with our live method for comparison
                live_trade = LiveTrade(symbol, "long", 10, 1)
                live_price = live_trade.get_current_price()
                
                if abs(price - live_price) < (price * 0.001):  # Within 0.1%
                    print(f"   ✅ Price consistency check passed")
                else:
                    print(f"   ⚠️ Price difference: ${abs(price - live_price):.6f}")
                    
            else:
                print(f"❌ {symbol}: Failed to get price")
                
        except Exception as e:
            print(f"❌ {symbol}: Error - {e}")

def run_live_comprehensive_tests():
    """Run all live data tests"""
    
    print("🧪 COMPREHENSIVE LIVE BINANCE DATA TEST SUITE")
    print("=" * 70)
    print(f"Test started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("🔴 USING LIVE MARKET DATA FROM BINANCE")
    print("=" * 70)
    
    try:
        # Check internet connection first
        print("🌐 Checking Binance API connection...")
        test_price = requests.get("https://fapi.binance.com/fapi/v1/ticker/price?symbol=BTCUSDT", timeout=5)
        if test_price.status_code == 200:
            price_data = test_price.json()
            print(f"✅ Connected! BTC Price: ${float(price_data['price']):.2f}")
        else:
            print("❌ Cannot connect to Binance API")
            return
        
        # Run all live tests
        test_live_stop_loss_logic()
        test_live_take_profit_logic()
        test_live_precision_edge_cases() 
        test_live_monitoring_simulation()
        test_multiple_symbols_live()
        test_monitoring_integration()
        
        print("\n" + "=" * 70)
        print("🎉 ALL LIVE DATA TESTS COMPLETED!")
        print("=" * 70)
        print("📋 LIVE TEST SUMMARY:")
        print("✅ Stop Loss logic tested with LIVE Binance prices")
        print("✅ Take Profit logic tested with LIVE market data")
        print("✅ Precision edge cases tested with real prices")
        print("✅ Live monitoring simulation completed")
        print("✅ Multiple symbols tested simultaneously")
        print("✅ Monitoring system integration verified")
        
        print("\n🚀 If all tests show ✅, your SL/TP logic works with LIVE market data!")
        print("💡 The system has been tested with real market conditions")
        
    except Exception as e:
        print(f"\n❌ LIVE TEST SUITE ERROR: {e}")
        print("Please check your internet connection and Binance API access.")

# Run the live comprehensive test suite
if __name__ == "__main__":
    run_live_comprehensive_tests()

🧪 COMPREHENSIVE LIVE BINANCE DATA TEST SUITE
======================================================================
Test started at: 2025-07-11 16:14:26
🔴 USING LIVE MARKET DATA FROM BINANCE
======================================================================
🌐 Checking Binance API connection...
✅ Connected! BTC Price: $117470.10
🔥 TESTING STOP LOSS LOGIC WITH LIVE BINANCE DATA
============================================================

📊 Testing LIVE BTCUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $113945.997000
   Take Profit: $124518.306000
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for BTCUSDT
   Entry: $117482.100000
   Stop Loss: $121006.563000
   Take Profit: $110433.174000
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   BTCUSDT Sample 1: $117470.100000
   BTCUSDT Sample 2: $117470.100000
   BTCUSDT Sample 3: $117470.100000

🔥 Testing LONG position SL logic:
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $113945.997000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $115120.698000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $113945.997000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $115120.698000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $113945.997000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $115120.698000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined

🔥 Testing SHORT position SL logic:
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $120994.203000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $119819.502000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $120994.203000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $119819.502000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $120994.203000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $119819.502000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $117470.100000: name 'self_monitoring_trader' is not defined

📊 Testing LIVE ETHUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for ETHUSDT
   Entry: $2981.190000
   Stop Loss: $2891.754300
   Take Profit: $3160.061400
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for ETHUSDT
   Entry: $2981.190000
   Stop Loss: $3070.625700
   Take Profit: $2802.318600
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   ETHUSDT Sample 1: $2981.190000
   ETHUSDT Sample 2: $2981.250000
   ETHUSDT Sample 3: $2981.250000

🔥 Testing LONG position SL logic:
   ❌ Error testing $2861.942400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2891.754300: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2921.566200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.190000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2862.000000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2891.812500: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2921.625000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.250000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2862.000000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2891.812500: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2921.625000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.250000: name 'self_monitoring_trader' is not defined

🔥 Testing SHORT position SL logic:
   ❌ Error testing $3100.437600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3070.625700: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3040.813800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.190000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3100.500000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3070.687500: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3040.875000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.250000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3100.500000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3070.687500: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3040.875000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2981.250000: name 'self_monitoring_trader' is not defined

📊 Testing LIVE SOLUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for SOLUSDT
   Entry: $163.260000
   Stop Loss: $158.362200
   Take Profit: $173.055600
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for SOLUSDT
   Entry: $163.260000
   Stop Loss: $168.157800
   Take Profit: $153.464400
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   SOLUSDT Sample 1: $163.260000
   SOLUSDT Sample 2: $163.260000
   SOLUSDT Sample 3: $163.260000

🔥 Testing LONG position SL logic:
   ❌ Error testing $156.729600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $158.362200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $159.994800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $156.729600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $158.362200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $159.994800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $156.729600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $158.362200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $159.994800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined

🔥 Testing SHORT position SL logic:
   ❌ Error testing $169.790400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $168.157800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $166.525200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $169.790400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $168.157800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $166.525200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $169.790400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $168.157800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $166.525200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $163.260000: name 'self_monitoring_trader' is not defined


🎯 TESTING TAKE PROFIT LOGIC WITH LIVE BINANCE DATA
============================================================

📊 Testing LIVE BTCUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $113945.997000
   Take Profit: $124518.306000
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $120994.203000
   Take Profit: $110421.894000
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   BTCUSDT Sample 1: $117470.100000
   BTCUSDT Sample 2: $117470.100000
   BTCUSDT Sample 3: $117470.100000

🎯 Testing LONG position TP logic:
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $124518.306000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $125693.007000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $129217.110000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $124518.306000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $125693.007000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $129217.110000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $122168.904000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $124518.306000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $125693.007000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $129217.110000: name 'self_monitoring_trader' is not defined

🎯 Testing SHORT position TP logic:
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $110421.894000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $109247.193000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $105723.090000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $110421.894000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $109247.193000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $105723.090000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $112771.296000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $110421.894000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $109247.193000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $105723.090000: name 'self_monitoring_trader' is not defined

📊 Testing LIVE ETHUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for ETHUSDT
   Entry: $2981.180000
   Stop Loss: $2891.744600
   Take Profit: $3160.050800
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for ETHUSDT
   Entry: $2981.140000
   Stop Loss: $3070.574200
   Take Profit: $2802.271600
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   ETHUSDT Sample 1: $2981.180000
   ETHUSDT Sample 2: $2981.140000
   ETHUSDT Sample 3: $2981.140000

🎯 Testing LONG position TP logic:
   ❌ Error testing $3100.427200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3160.050800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3189.862600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3279.298000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3100.385600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3160.008400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3189.819800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3279.254000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3100.385600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3160.008400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3189.819800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $3279.254000: name 'self_monitoring_trader' is not defined

🎯 Testing SHORT position TP logic:
   ❌ Error testing $2861.932800: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2802.309200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2772.497400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2683.062000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2861.894400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2802.271600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2772.460200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2683.026000: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2861.894400: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2802.271600: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2772.460200: name 'self_monitoring_trader' is not defined
   ❌ Error testing $2683.026000: name 'self_monitoring_trader' is not defined

📊 Testing LIVE ADAUSDT Data
----------------------------------------
📊 Created LIVE LONG trade for ADAUSDT
   Entry: $0.686500
   Stop Loss: $0.665905
   Take Profit: $0.727690
   Margin: $100 | Leverage: 5x
📊 Created LIVE SHORT trade for ADAUSDT
   Entry: $0.686500
   Stop Loss: $0.707095
   Take Profit: $0.645310
   Margin: $100 | Leverage: 5x
📡 Fetching 3 live price samples from Binance...
   ADAUSDT Sample 1: $0.686500
   ADAUSDT Sample 2: $0.686400
   ADAUSDT Sample 3: $0.686500

🎯 Testing LONG position TP logic:
   ❌ Error testing $0.713960: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.727690: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.734555: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.755150: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.713856: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.727584: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.734448: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.755040: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.713960: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.727690: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.734555: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.755150: name 'self_monitoring_trader' is not defined

🎯 Testing SHORT position TP logic:
   ❌ Error testing $0.659040: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.645310: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.638445: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.617850: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.658944: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.645216: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.638352: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.617760: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.659040: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.645310: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.638445: name 'self_monitoring_trader' is not defined
   ❌ Error testing $0.617850: name 'self_monitoring_trader' is not defined


🔬 TESTING LIVE PRECISION EDGE CASES
============================================================

📊 Precision test for BTCUSDT
----------------------------------------
📊 Created LIVE LONG trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $113945.997000
   Take Profit: $124518.306000
   Margin: $50 | Leverage: 5x
Live Price: $117470.10000000
Stop Loss: $113945.99700000
Take Profit: $124518.30600000

🔬 Stop Loss precision tests:
❌ Error testing precision for BTCUSDT: name 'self_monitoring_trader' is not defined

📊 Precision test for ETHUSDT
----------------------------------------
📊 Created LIVE LONG trade for ETHUSDT
   Entry: $2981.140000
   Stop Loss: $2891.705800
   Take Profit: $3160.008400
   Margin: $50 | Leverage: 5x
Live Price: $2981.14000000
Stop Loss: $2891.70580000
Take Profit: $3160.00840000

🔬 Stop Loss precision tests:
❌ Error testing precision for ETHUSDT: name 'self_monitoring_trader' is not defined

📊 Precision test for DOGEUSDT
----------------------------------------
📊 Created LIVE LONG trade for DOGEUSDT
   Entry: $0.195210
   Stop Loss: $0.189354
   Take Profit: $0.206923
   Margin: $50 | Leverage: 5x
Live Price: $0.19521000
Stop Loss: $0.18935370
Take Profit: $0.20692260

🔬 Stop Loss precision tests:
❌ Error testing precision for DOGEUSDT: name 'self_monitoring_trader' is not defined


🔄 TESTING LIVE MONITORING SIMULATION
============================================================
📊 Creating live monitoring simulation for BTCUSDT
📊 Created LIVE LONG trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $113945.997000
   Take Profit: $124518.306000
   Margin: $100 | Leverage: 5x

🤖 Simulating monitoring checks...
Current entry: $117470.100000
Stop Loss at: $113945.997000
Take Profit at: $124518.306000

--- Monitoring Cycle 1 ---
Live Price: $117470.100000 (+0.000%)
❌ Error in monitoring simulation: name 'self_monitoring_trader' is not defined


🌐 TESTING MULTIPLE SYMBOLS WITH LIVE DATA
============================================================
📊 Creating live trades for multiple symbols...
📊 Created LIVE LONG trade for BTCUSDT
   Entry: $117470.100000
   Stop Loss: $113945.997000
   Take Profit: $124518.306000
   Margin: $50 | Leverage: 3x
📊 Created LIVE LONG trade for ETHUSDT
   Entry: $2981.140000
   Stop Loss: $2891.705800
   Take Profit: $3160.008400
   Margin: $50 | Leverage: 3x
📊 Created LIVE LONG trade for SOLUSDT
   Entry: $163.270000
   Stop Loss: $158.371900
   Take Profit: $173.066200
   Margin: $50 | Leverage: 3x
📊 Created LIVE LONG trade for ADAUSDT
   Entry: $0.686500
   Stop Loss: $0.665905
   Take Profit: $0.727690
   Margin: $50 | Leverage: 3x

🔄 Testing 4 live trades simultaneously...
❌ Error testing BTCUSDT: name 'self_monitoring_trader' is not defined
❌ Error testing ETHUSDT: name 'self_monitoring_trader' is not defined
❌ Error testing SOLUSDT: name 'self_monitoring_trader' is not defined
❌ Error testing ADAUSDT: name 'self_monitoring_trader' is not defined


🔄 TESTING MONITORING SYSTEM INTEGRATION
============================================================
❌ Error getting monitoring status: name 'self_monitoring_trader' is not defined

Checking fixed methods:

❌ LIVE TEST SUITE ERROR: name 'self_monitoring_trader' is not defined
Please check your internet connection and Binance API access.